version: '3.8'

services:

  mariadb:
    container_name: fcfs-mariadb
    image: mariadb:10.8.3
    ports:
      - "12779:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "fcfs_db"
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
