
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:12779/fcfs_db
    username: root
    password: '0000'
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000
      connection-init-sql: SELECT 1
      minimum-idle: 20
      idle-timeout: 600000
      max-lifetime: 60000


  jpa:
    hibernate:
      ddl-auto: create
decorator:
  datasource:
    p6spy:
      enable-logging: true
