
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:12779/fcfs_db
    username: root
    password: '0000'
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000



  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

  redis:
    host: localhost
    port: 12889

decorator:
  datasource:
    p6spy:
      enable-logging: true

#logging:
#  level:
#    root: debug
logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

