
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:12779/fcfs_db
    username: root
    password: '0000'


  jpa:
    hibernate:
      ddl-auto: create

  redis:
    host: localhost
    port: 12889

decorator:
  datasource:
    p6spy:
      enable-logging: true
